<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <script>
        try{
            console.log("Starting of Try")
            blabla; //This will cause an error
            console.log("Ending of Try")
        }
        catch(err){
            //console.log("An Error has been Occured")

            console.log(err) //This will tell us, in which line number the error has been occured

        }

        //In order to use Try and Catch with setTimeOut function, we must have to apply the Try and Catch statements inside the setTimeOut() function
        setTimeout(function(){
            try{
                gujuguju;
            }
            catch(err){
                console.log(err)
                console.log(err.name) //It will display the name of an error
                console.log(err.message) //It will display the message of an error
                console.log(err.stack) //It will display the fully stack (name + messgae) of an error.

                if(err instanceof ReferenceError){

                console.log("Its a Reference Error brooo")

                }
                else if(err instanceof TypeError){

                console.log("Its a Type Error Brooooo")

                }
                else{
                console.log("I dont wanna talk about any those of errors. Yuck Fou!")
                }
            }
        },1500)

        //Real Life Example of Try and Catch ðŸ˜Ž
        console.log("Real Life Example of Try & Catch ðŸ‘‡")
        try{
            let json = '{"name":"Rahul Saw" , "age":21}'
            let user = JSON.parse(json) //JSON.parse is used to convert the json into objects

            if(!user.name){
                throw new Error("Incomplete data: NO NAME") //With the help of this you can show your desired error name. In order to perform this, kindly remove the name property from JSON data
            }

            console.log(user.name)
            console.log(user.age)
        }
        catch(errr){
            console.log(errr)
        }
        //Irrespective of try and catch the 'finally' will always run either try runs or not , or catch runs or not, 'finally' will always run.
        finally{
            console.log("Finally you can run!")
        }
    </script>
</body>
</html>